apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-secrets

resources:
  - ../base/helmrelease.yaml

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: mcp-stack
